### ISSUE TITLE
Integrate Liascript markdown parser

### ISSUE THREAD

**Issue by bastiion** [fsfw-dresden/schulstick-portal#3]
LiaScript is already a well established stadard for markdown based lessons and OER material.

Try to adopt that to out lector pipeline and evaluate it's use

https://liascript.github.io/course/?https://raw.githubusercontent.com/andre-dietrich/e-Learning-2019/master/README.md

**Comment by eMPee584** [comment]
- [LiaScript/CheetSheet](https://github.com/LiaScript/CheetSheet)
